In [44]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
from sklearn import preprocessing

In [2]:
path_metrics = "../../Results/NST_metrics/merged.csv"

In [3]:
metrics = pd.read_csv(path_metrics, index_col=0)
metrics.head(3)

Image_path  \
0  /home/durrmeyer/Images/StyleTransferImages/All...   
1  /home/durrmeyer/Images/StyleTransferImages/All...   
2  /home/durrmeyer/Images/StyleTransferImages/All...   

                                            filename           type  \
0  BOULDERxFISH01_colorcontrolOFF_1vs1e3_TVlossON...  fish stylized   
1  BOULDERxFISH01_colorcontrolON_1vs1e3_TVlossON_...  fish stylized   
2  BOULDERxFISH02_colorcontrolOFF_1vs1e3_TVlossON...  fish stylized   

       folder  habitat color_control tv_loss      layers  sex  fish_n  ...  \
0  All_layers  BOULDER           OFF      ON  All_layers  NaN     1.0  ...   
1  All_layers  BOULDER            ON      ON  All_layers  NaN     1.0  ...   
2  All_layers  BOULDER           OFF      ON  All_layers  NaN     2.0  ...   

  ('count_LBP_value', 16.0, 4.0, 62913.600000000006)_False_False_DARTER_GRAY_nan_nan  \
0                                             1706.0                                   
1                                             1667.0                                   
2                                             1811.0                                   

   ('count_LBP_value', 16.0, 4.0, 63568.95)_False_False_DARTER_GRAY_nan_nan  \
0                                             1299.0                          
1                                             1276.0                          
2                                             1401.0                          

   ('count_LBP_value', 16.0, 4.0, 64224.3)_False_False_DARTER_GRAY_nan_nan  \
0                                             3295.0                         
1                                             3350.0                         
2                                             3290.0                         

  ('count_LBP_value', 16.0, 4.0, 64879.65)_False_False_DARTER_GRAY_nan_nan  \
0                                            16098.0                         
1                                            16214.0                         
2                                            16110.0                         

  mean_stat_False_False_DARTER_GRAY_nan_nan  \
0                                682.983582   
1                                686.982056   
2                                679.134338   

   std_stat_False_False_DARTER_GRAY_nan_nan  \
0                                 73.672249   
1                                 73.745628   
2                                 73.305389   

   skewness_stat_False_False_DARTER_GRAY_nan_nan  \
0                                       1.029604   
1                                       0.982984   
2                                       1.303150   

  kurtosis_stat_False_False_DARTER_GRAY_nan_nan  \
0                                      1.011339   
1                                      0.821433   
2                                      1.534922   

  entropy_stat_False_False_DARTER_GRAY_nan_nan  \
0                                    11.368481   
1                                    11.368526   
2                                    11.368526   

   gini_coefficient_False_False_DARTER_GRAY_nan_nan  
0                                          0.058247  
1                                          0.058208  
2                                          0.056474  

[3 rows x 741 columns]

In [4]:
columns_info=metrics.columns[:19]
print(columns_info)

Index(['Image_path', 'filename', 'type', 'folder', 'habitat', 'color_control',
       'tv_loss', 'layers', 'sex', 'fish_n', 'species', 'img_width',
       'img_height', 'image_extension',
       'Image_path____False_False_DARTER_GRAY_nan_nan',
       'normalization____False_False_DARTER_GRAY_nan_nan',
       'standardization____False_False_DARTER_GRAY_nan_nan',
       'image_type____False_False_DARTER_GRAY_nan_nan',
       'channel_image____False_False_DARTER_GRAY_nan_nan'],
      dtype='object')


In [5]:
metric_values = metrics.drop(columns_info, axis=1)
metric_info = metrics[columns_info]
metric_values.head()

value_LBP_8.0_2.0_0.0_False_False_DARTER_GRAY_nan_nan  \
0                                              255.0       
1                                              255.0       
2                                              255.0       
3                                              255.0       
4                                              255.0       

   value_LBP_8.0_2.0_1.0_False_False_DARTER_GRAY_nan_nan  \
0                                                0.0       
1                                                0.0       
2                                                0.0       
3                                                0.0       
4                                                0.0       

   value_LBP_8.0_2.0_2.0_False_False_DARTER_GRAY_nan_nan  \
0                                               30.0       
1                                               30.0       
2                                               30.0       
3                                               30.0       
4                                               30.0       

   value_LBP_8.0_2.0_3.0_False_False_DARTER_GRAY_nan_nan  \
0                                               15.0       
1                                               15.0       
2                                              225.0       
3                                              225.0       
4                                              225.0       

   value_LBP_8.0_2.0_4.0_False_False_DARTER_GRAY_nan_nan  \
0                                              225.0       
1                                              225.0       
2                                               15.0       
3                                               15.0       
4                                               15.0       

   value_LBP_8.0_2.0_5.0_False_False_DARTER_GRAY_nan_nan  \
0                                               14.0       
1                                               14.0       
2                                               14.0       
3                                               14.0       
4                                               14.0       

   value_LBP_8.0_2.0_6.0_False_False_DARTER_GRAY_nan_nan  \
0                                               31.0       
1                                               31.0       
2                                               31.0       
3                                               31.0       
4                                               31.0       

   value_LBP_8.0_2.0_7.0_False_False_DARTER_GRAY_nan_nan  \
0                                              240.0       
1                                              240.0       
2                                              240.0       
3                                              240.0       
4                                              240.0       

   value_LBP_8.0_2.0_8.0_False_False_DARTER_GRAY_nan_nan  \
0                                              224.0       
1                                              224.0       
2                                              224.0       
3                                              224.0       
4                                                1.0       

   value_LBP_8.0_2.0_9.0_False_False_DARTER_GRAY_nan_nan  ...  \
0                                              241.0      ...   
1                                              241.0      ...   
2                                              241.0      ...   
3                                              241.0      ...   
4                                              241.0      ...   

   ('count_LBP_value', 16.0, 4.0, 62913.600000000006)_False_False_DARTER_GRAY_nan_nan  \
0                                             1706.0                                    
1                                             1667.0                                    
2                                             1811.0                                    
3      

In [6]:
min_max_scaler = preprocessing.MinMaxScaler()
scaled_values = pd.DataFrame(min_max_scaler.fit_transform(metric_values), columns=metric_values.columns)
scaled_values.head()

value_LBP_8.0_2.0_0.0_False_False_DARTER_GRAY_nan_nan  \
0                                                1.0       
1                                                1.0       
2                                                1.0       
3                                                1.0       
4                                                1.0       

   value_LBP_8.0_2.0_1.0_False_False_DARTER_GRAY_nan_nan  \
0                                                0.0       
1                                                0.0       
2                                                0.0       
3                                                0.0       
4                                                0.0       

   value_LBP_8.0_2.0_2.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.114173       
1                                           0.114173       
2                                           0.114173       
3                                           0.114173       
4                                           0.114173       

   value_LBP_8.0_2.0_3.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.059761       
1                                           0.059761       
2                                           0.896414       
3                                           0.896414       
4                                           0.896414       

   value_LBP_8.0_2.0_4.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.885375       
1                                           0.885375       
2                                           0.055336       
3                                           0.055336       
4                                           0.055336       

   value_LBP_8.0_2.0_5.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.055118       
1                                           0.055118       
2                                           0.055118       
3                                           0.055118       
4                                           0.055118       

   value_LBP_8.0_2.0_6.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.122047       
1                                           0.122047       
2                                           0.122047       
3                                           0.122047       
4                                           0.122047       

   value_LBP_8.0_2.0_7.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.944664       
1                                           0.944664       
2                                           0.944664       
3                                           0.944664       
4                                           0.944664       

   value_LBP_8.0_2.0_8.0_False_False_DARTER_GRAY_nan_nan  \
0                                           0.881423       
1                                           0.881423       
2                                           0.881423       
3                                           0.881423       
4                                           0.000000       

   value_LBP_8.0_2.0_9.0_False_False_DARTER_GRAY_nan_nan  ...  \
0                                           0.948819      ...   
1                                           0.948819      ...   
2                                           0.948819      ...   
3                                           0.948819      ...   
4                                           0.948819      ...   

   ('count_LBP_value', 16.0, 4.0, 62913.600000000006)_False_False_DARTER_GRAY_nan_nan  \
0                                           0.006921                                    
1                                           0.006510                                    
2                                           0.008027                                    
3      

Is the mse from a prediction correlated to the habitat?

In [11]:
from sklearn.linear_model import RidgeClassifier
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.dummy import DummyClassifier

In [43]:
classe = "habitat"

my_data = scaled_values.merge(metric_info, how='inner', left_index=True, right_index=True).dropna(subset=[classe])

train, test = train_test_split(my_data, test_size=0.2)

X_train = train[scaled_values.columns]
X_test = test[scaled_values.columns]

y_train = train[classe]
y_test = test[classe]

y_train.head()

157        DETRITUS
78          BOULDER
89     BOULDERxSAND
19     BOULDERxSAND
26         DETRITUS
Name: habitat, dtype: object

In [ ]:
def visu_log_reg(data, explicative, target, title):
    #plot correlations of explicative var
    corr = data[explicative].corr()
    cmap = sns.diverging_palette(230, 20, as_cmap=True)
    sns.heatmap(corr, cmap=cmap, vmax=.3, center=0,
            square=True, linewidths=.5, cbar_kws={"shrink": .5}, annot=True)
    plt.show()
    
    #plot histogram of target
    sns.histplot(data=data, x=explicative, hue=target, kde=True, stat="probability", common_norm=False).set_title(title)
    plt.show()    
    #do log reg
    
    sns.
    
    
visu_log_reg(my_data, "mse", "folder", "logistic reg of folders by mse")

In [37]:
dummy = DummyClassifier(strategy="stratified")
dummy.fit(X_train, y_train)
print(dummy.score(X_train, y_train))
print(dummy.score(X_test, y_test))

0.14
0.21052631578947367


In [38]:
neigh = KNeighborsClassifier(n_neighbors=6)
neigh.fit(X_train, y_train.values.ravel())
y_pred = neigh.predict(X_test)
print(neigh.score(X_train, y_train))
print(neigh.score(X_test, y_test))

0.8466666666666667
0.5526315789473685


In [39]:
reg = LogisticRegression().fit(X_train, y_train.values.ravel())
print(reg.score(X_train, y_train))
print(reg.score(X_test, y_test))

1.0
0.8421052631578947


/home/durrmeyer/anaconda3/envs/cefe/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
SVM = svm.SVC()
SVM.fit(X_train, y_train.values.ravel())
print("score: ",SVM.score(X_test,y_test))
y_pred = SVM.predict(X_test)
print("confusion matrix: \n",confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

score:  0.6578947368421053
confusion matrix: 
 [[6 0 0 0 0 0]
 [0 5 0 0 0 0]
 [0 2 4 0 1 1]
 [0 0 0 4 0 0]
 [0 0 0 1 4 1]
 [0 1 6 0 0 2]]
              precision    recall  f1-score   support

     BOULDER       1.00      1.00      1.00         6
BOULDERxSAND       0.62      1.00      0.77         5
    DETRITUS       0.40      0.50      0.44         8
      GRAVEL       0.80      1.00      0.89         4
      PLANTS       0.80      0.67      0.73         6
        SAND       0.50      0.22      0.31         9

    accuracy                           0.66        38
   macro avg       0.69      0.73      0.69        38
weighted avg       0.65      0.66      0.63        38



In [13]:
RF = RandomForestClassifier(n_estimators=1000, max_depth=10, random_state=0).fit(X_train, y_train)
RF.predict(X_test)
round(RF.score(X_test, y_test), 4)

0.9737